/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VacationIndexRouteImport } from './routes/vacation/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as WarehouseSummaryRouteImport } from './routes/warehouse/summary'
import { Route as WarehouseOrdersRouteImport } from './routes/warehouse/orders'
import { Route as WarehouseNewOrderRouteImport } from './routes/warehouse/new-order'
import { Route as VacationMyRouteImport } from './routes/vacation/my'
import { Route as VacationEmployeesRouteImport } from './routes/vacation/employees'
import { Route as PatientsPatientIdRouteImport } from './routes/patients/$patientId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationIndexRoute = VacationIndexRouteImport.update({
  id: '/vacation/',
  path: '/vacation/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseSummaryRoute = WarehouseSummaryRouteImport.update({
  id: '/warehouse/summary',
  path: '/warehouse/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseOrdersRoute = WarehouseOrdersRouteImport.update({
  id: '/warehouse/orders',
  path: '/warehouse/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseNewOrderRoute = WarehouseNewOrderRouteImport.update({
  id: '/warehouse/new-order',
  path: '/warehouse/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationMyRoute = VacationMyRouteImport.update({
  id: '/vacation/my',
  path: '/vacation/my',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationEmployeesRoute = VacationEmployeesRouteImport.update({
  id: '/vacation/employees',
  path: '/vacation/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/vacation/employees': typeof VacationEmployeesRoute
  '/vacation/my': typeof VacationMyRoute
  '/warehouse/new-order': typeof WarehouseNewOrderRoute
  '/warehouse/orders': typeof WarehouseOrdersRoute
  '/warehouse/summary': typeof WarehouseSummaryRoute
  '/attendance': typeof AttendanceIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/users': typeof UsersIndexRoute
  '/vacation': typeof VacationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/vacation/employees': typeof VacationEmployeesRoute
  '/vacation/my': typeof VacationMyRoute
  '/warehouse/new-order': typeof WarehouseNewOrderRoute
  '/warehouse/orders': typeof WarehouseOrdersRoute
  '/warehouse/summary': typeof WarehouseSummaryRoute
  '/attendance': typeof AttendanceIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/users': typeof UsersIndexRoute
  '/vacation': typeof VacationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/vacation/employees': typeof VacationEmployeesRoute
  '/vacation/my': typeof VacationMyRoute
  '/warehouse/new-order': typeof WarehouseNewOrderRoute
  '/warehouse/orders': typeof WarehouseOrdersRoute
  '/warehouse/summary': typeof WarehouseSummaryRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/vacation/': typeof VacationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/patients/$patientId'
    | '/vacation/employees'
    | '/vacation/my'
    | '/warehouse/new-order'
    | '/warehouse/orders'
    | '/warehouse/summary'
    | '/attendance'
    | '/incidents'
    | '/patients'
    | '/users'
    | '/vacation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/patients/$patientId'
    | '/vacation/employees'
    | '/vacation/my'
    | '/warehouse/new-order'
    | '/warehouse/orders'
    | '/warehouse/summary'
    | '/attendance'
    | '/incidents'
    | '/patients'
    | '/users'
    | '/vacation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/patients/$patientId'
    | '/vacation/employees'
    | '/vacation/my'
    | '/warehouse/new-order'
    | '/warehouse/orders'
    | '/warehouse/summary'
    | '/attendance/'
    | '/incidents/'
    | '/patients/'
    | '/users/'
    | '/vacation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  VacationEmployeesRoute: typeof VacationEmployeesRoute
  VacationMyRoute: typeof VacationMyRoute
  WarehouseNewOrderRoute: typeof WarehouseNewOrderRoute
  WarehouseOrdersRoute: typeof WarehouseOrdersRoute
  WarehouseSummaryRoute: typeof WarehouseSummaryRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  VacationIndexRoute: typeof VacationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacation/': {
      id: '/vacation/'
      path: '/vacation'
      fullPath: '/vacation'
      preLoaderRoute: typeof VacationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/summary': {
      id: '/warehouse/summary'
      path: '/warehouse/summary'
      fullPath: '/warehouse/summary'
      preLoaderRoute: typeof WarehouseSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/orders': {
      id: '/warehouse/orders'
      path: '/warehouse/orders'
      fullPath: '/warehouse/orders'
      preLoaderRoute: typeof WarehouseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/new-order': {
      id: '/warehouse/new-order'
      path: '/warehouse/new-order'
      fullPath: '/warehouse/new-order'
      preLoaderRoute: typeof WarehouseNewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacation/my': {
      id: '/vacation/my'
      path: '/vacation/my'
      fullPath: '/vacation/my'
      preLoaderRoute: typeof VacationMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacation/employees': {
      id: '/vacation/employees'
      path: '/vacation/employees'
      fullPath: '/vacation/employees'
      preLoaderRoute: typeof VacationEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  VacationEmployeesRoute: VacationEmployeesRoute,
  VacationMyRoute: VacationMyRoute,
  WarehouseNewOrderRoute: WarehouseNewOrderRoute,
  WarehouseOrdersRoute: WarehouseOrdersRoute,
  WarehouseSummaryRoute: WarehouseSummaryRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  VacationIndexRoute: VacationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
